services:
  stable-diffusion:
    user: "1000:1000"
    image: stable-diffusion-webui
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automatic1111
    environment:
      - COMMANDLINE_ARGS=--xformers --enable-insecure-extension-access --no-half-vae --api --no-download-sd-model --data-dir "/home/sdwui/data" --embeddings-dir "/home/sdwui/data/embeddings" --port 7860 --listen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility]
    volumes:
      - ./venv:/home/sdwui/stable-diffusion-webui/venv
      - ./repositories:/home/sdwui/stable-diffusion-webui/repositories
      - ./config/webui-user.sh:/home/sdwui/stable-diffusion-webui/webui-user.sh
      - ./data:/home/sdwui/data
    ports:
      - "7860:7860"
    networks:
      - sd-network
    tty: true 

networks:
  sd-network:
    name: sd-network
    driver: bridge