services:
  stable-diffusion:
    user: "1000:1000"
    image: stable-diffusion-webui
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automatic1111
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - COMMANDLINE_ARGS=--xformers --enable-insecure-extension-access --api --no-download-sd-model --ui-config-file json-configs/ui-config.json --ui-settings-file json-configs/config.json --listen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    volumes:
      - ./models:/home/sdwui/stable-diffusion-webui/models
      - ./extensions:/home/sdwui/stable-diffusion-webui/extensions
      - ./extras/embeddings:/home/sdwui/stable-diffusion-webui/embeddings
      - ./venv:/home/sdwui/stable-diffusion-webui/venv
      - ./outputs:/home/sdwui/stable-diffusion-webui/outputs
      - ./repositories:/home/sdwui/stable-diffusion-webui/repositories
      - ./config/webui-user.sh:/home/sdwui/stable-diffusion-webui/webui-user.sh
      - ./config/webui.sh:/home/sdwui/stable-diffusion-webui/webui.sh
      - ./json-configs:/home/sdwui/stable-diffusion-webui/json-configs
    ports:
      - "7860:7860"
    tty: true  # Esto mantiene el contenedor abierto
